### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by josezy** [josezy/vannelope#2]
- [x] animaciones de movimiento/rebote, arriba/abajo, fade in, scroll stack
- [x] animación letras
- [x] parallax
- [x] animación zorro (centro a navbar)
- [x] display image on hover (section 2)
- [x] responsiveness
